default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rasi-db
  password: rasi2023
  host: 10.110.16.3

development:
  <<: *default
  database: pacientes-db